INSERT INTO POC_USER(ID, NAME) VALUES (1, 'Antonio');
INSERT INTO POC_USER(ID, NAME) VALUES (2, 'Mauricio');
INSERT INTO POC_USER(ID, NAME) VALUES (3, 'Ricardo');
INSERT INTO POC_USER(ID, NAME) VALUES (4, 'Tarcisio');
